name: Manual Checkout (Advanced)

on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a

      - name: Manual Git Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git fetch origin
          git checkout main

      - name: List files after checkout
        run: ls -a
