name: Variables and Secrets
on: [push]

jobs:
  staging-test:
    runs-on: ubuntu-latest
    environment: staging  # Uses staging environment secrets
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "✅ BOOLEAN_SECRET is true - I ran!"
      - name: Log Vars
        run: |

          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR" 
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"