name: Convert YAML to JSON

on: 
  push:
    paths:
      - 'input.yaml'   # Only triggers when input.yaml changes

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Convert YAML to JSON
        run: node convert.js

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: View macOS version
        run: sw_vers

  dependent-job:
    runs-on: ubuntu-latest
    needs: convert      # This job runs **after convert** finishes
    steps:
      - name: Echo a string
        run: echo "This is a dependent job"

      - name: Error Step
        run: doesnot-exist-command   # This will fail
